development:
  adapter: postgresql
  database: bootie_tracker_dev
  encoding: unicode
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: bootie_tracker_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: bootie_tracker_production
  pool: 5
