development:
  adapter: postgresql
  database: booty_tracker_dev
  encoding: unicode
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: booty_tracker_test
  pool: 5
  timeout: 5000
